version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://dcmon:dcmon@db:5432/dcmon
    depends_on:
      - db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5001

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=dcmon
      - POSTGRES_PASSWORD=dcmon
      - POSTGRES_DB=dcmon
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
