version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/dcmon
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5001

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
