"""Initial migration

Revision ID: 261062bd3c0e
Revises: 
Create Date: 2025-01-19 15:13:13.131799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '261062bd3c0e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_checked', sa.DateTime(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.drop_column('state')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('dependencies')
        batch_op.drop_column('shutdown_order')
        batch_op.drop_column('completed')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('shutdown_order', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('dependencies', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('last_checked')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
