"""Add application state

Revision ID: 756e668c8911
Revises: 
Create Date: 2025-01-18 21:49:18.546011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756e668c8911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
